<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\KLCode.Wpf\KLCode.Wpf.csproj" />
    <ProjectReference Include="..\KLA.ModelStartupImporter.Core\KLA.ModelStartupImporter.Core.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
    <AssemblyName>KLA.ModelStartupImporter.UI_2024</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <AssemblyName>KLA.ModelStartupImporter.UI</AssemblyName>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
